<?php
	date_default_timezone_set("Etc/GMT-1");
	$year = date("Y");
	$month = date("m");
	$week = date("W");
	$month_name = date("M");
	$day = date("d");
	$day_name = date("D");
	$hours = date("H");
	$mins = date("i");
	$secs = date("s");
	$month_arr = array();
	$day_arr = array();
	$week_days = array();
	$month_arr["01"] = ["يناير","Janvier","ⵢⴻⵏⵏⴰⵢⵔ"];
	$month_arr["02"] = ["فبراير","Février","ⵢⴻⴱⵔⴰⵢⵔ"];
	$month_arr["03"] = ["مارس","Mars","ⵎⴰⵕⵙ"];
	$month_arr["04"] = ["أبريل","Avril","ⵉⴱⵔⵉⵍ"];
	$month_arr["05"] = ["ماي","Mai","ⵎⴰⵢ"];
	$month_arr["06"] = ["يونيو","Juin","ⵢⵓⵏⵢⵓ"];
	$month_arr["07"] = ["يوليوز","Juillet","ⵢⵓⵍⵢⵓⵣ"];
	$month_arr["08"] = ["غشت","Aout","ⵖⵓⵛⵜ"];
	$month_arr["09"] = ["شتنبر","Septembre","ⵛⵓⵜⴰⵏⴱⵉⵔ"];
	$month_arr["10"] = ["أكتوبر","Octobre","ⴽⵜⵓⴱⵔ"];
	$month_arr["11"] = ["نونبر","Novembre","ⵏⵓⵡⴻⵏⴱⵔ"];
	$month_arr["12"] = ["دجنبر","Décembre","ⴷⵓⵊⴰⵏⴱⵉⵔ"];
	$day_arr["Mon"] = ["الإثنين","Lundi","ⴰⵢⵏⴰⵙ"];
	$day_arr["Tue"] = ["الثلاثاء","Mardi","ⴰⵙⵉⵏⴰⵙ"];
	$day_arr["Wed"] = ["الأربعاء","Mercredi","ⴰⴽⵕⴰⵙ"];
	$day_arr["Thu"] = ["الخميس","Jeudi","ⴰⴽⵡⴰⵙ"];
	$day_arr["Fri"] = ["الجمعة","Vendredi","ⴰⵙⵉⵎⵡⴰⵙ"];
	$day_arr["Sat"] = ["السبت","Samedi","ⴰⵚⵉⴹⵢⴰⵙ"];
	$day_arr["Sun"] = ["الأحد","Dimanche","ⴰⵙⴰⵎⴰⵙ"];
	$dayn["ar"][0] = $day_arr["Mon"][0];
	$dayn["ar"][1] = $day_arr["Tue"][0];
	$dayn["ar"][2] = $day_arr["Wed"][0];
	$dayn["ar"][3] = $day_arr["Thu"][0];
	$dayn["ar"][4] = $day_arr["Fri"][0];
	$dayn["ar"][5] = $day_arr["Sat"][0];
	$dayn["ar"][6] = $day_arr["Sun"][0];
	$dayn["fr"][0] = $day_arr["Mon"][0];
	$dayn["fr"][1] = $day_arr["Tue"][1];
	$dayn["fr"][2] = $day_arr["Wed"][1];
	$dayn["fr"][3] = $day_arr["Thu"][1];
	$dayn["fr"][4] = $day_arr["Fri"][1];
	$dayn["fr"][5] = $day_arr["Sat"][1];
	$dayn["fr"][6] = $day_arr["Sun"][1];
	$dayn["az"][0] = $day_arr["Mon"][2];
	$dayn["az"][1] = $day_arr["Tue"][2];
	$dayn["az"][2] = $day_arr["Wed"][2];
	$dayn["az"][3] = $day_arr["Thu"][2];
	$dayn["az"][4] = $day_arr["Fri"][2];
	$dayn["az"][5] = $day_arr["Sat"][2];
	$dayn["az"][6] = $day_arr["Sun"][2];
	$full_date_ar = $day_arr[$day_name][0]." <span class='text-success'>".$day."</span> ".$month_arr[$month][0]." <span class='text-success'>".$year."</span>";
	$full_date_fr = $day_arr[$day_name][1]." <span class='text-success'>".$day."</span> ".$month_arr[$month][1]." <span class='text-success'>".$year."</span>";
	$full_date_az = $day_arr[$day_name][2]." <span class='text-success'>".$day."</span> ".$month_arr[$month][2]." <span class='text-success'>".$year."</span>";
	$season = '2017/2018';
?>